version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: lianghua_mysql
    environment:
      MYSQL_ROOT_PASSWORD: lianghua123
      MYSQL_DATABASE: quantdb
      MYSQL_USER: quant
      MYSQL_PASSWORD: quant123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: lianghua_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Jupyter Notebook开发环境
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: lianghua_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - ./notebooks:/workspace/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  # 监控Web应用
  web_monitor:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: lianghua_monitor
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://quant:quant123@mysql:3306/quantdb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: