# 配置热更新管理器模块配置
# Hot Reload Manager Module Configuration

# 热更新配置
hot_reload_config:
  # 监控目录和文件
  watch_directories:
    - "./config"
    - "./quant_system/config"
  watch_files:
    - "./app.json"
    - "./system.yaml"
  file_patterns:
    - "*.json"
    - "*.yaml" 
    - "*.yml"
    - "*.toml"
  
  # 热更新行为配置
  auto_reload: true
  backup_count: 10
  validation_timeout: 30.0
  rollback_timeout: 300.0
  change_detection_interval: 1.0
  enable_version_control: true
  enable_change_validation: true

# 验证标准配置
validation_standards:
  # 配置覆盖率阈值
  config_coverage_threshold: 0.95
  
  # 配置完整度阈值
  config_completeness_threshold: 0.98
  
  # 关键配置项非空率阈值
  critical_config_threshold: 1.0
  
  # 配置更新延迟阈值（秒）
  config_freshness_seconds: 60
  
  # 质量评分阈值
  quality_score_threshold: 80.0

# 验证规则配置
validation_rules:
  # 完整性规则
  completeness_rules:
    required_config_validation:
      enabled: true
      critical_configs:
        - "database.host"
        - "database.port"
        - "redis.host"
        - "redis.port"
        - "storage_layers"
      
    config_count_validation:
      enabled: true
      expected_config_sections:
        - "data_sources"
        - "storage"
        - "monitoring"
        
  # 准确性规则
  accuracy_rules:
    # 数值范围验证
    numeric_range_validation:
      enabled: true
      port_range: [1, 65535]
      timeout_range: [1, 3600]
      
    # 格式验证
    format_validation:
      enabled: true
      url_format: "^https?://.*"
      host_format: "^[a-zA-Z0-9.-]+$"
      
  # 一致性规则
  consistency_rules:
    # 跨配置文件一致性
    cross_config_consistency:
      enabled: true
      reference_integrity: true
      
    # 配置依赖一致性
    dependency_consistency:
      enabled: true
      check_service_dependencies: true

# 缺口检测配置
gap_detection:
  enabled: true
  consecutive_gap_threshold: 5
  max_analysis_configs: 50
  tolerance:
    single_config_tolerance: 0.02  # 2%
    consecutive_tolerance: 0.005  # 0.5%
    overall_tolerance: 0.05  # 5%

# 报告配置
report_config:
  output_dir: "./reports/config"
  filename_format: "hot_reload_report_{timestamp}"
  formats:
    - json
    - markdown
    - html
  content:
    include_detailed_errors: true
    include_config_details: true
    include_config_samples: false
    include_performance_metrics: true
  retention:
    retention_days: 30
    auto_cleanup: true

# 性能配置
performance:
  concurrency:
    max_concurrent_tasks: 10
    connection_timeout: 30
    operation_timeout: 300
  memory:
    batch_size: 1000
    max_memory_mb: 512
  cache:
    enabled: true
    ttl_seconds: 3600
    max_size: 1000

# 告警配置
alerting:
  enabled: true
  thresholds:
    overall_score_threshold: 70
    error_config_threshold: 2
    freshness_alert_threshold: 300  # 5分钟
  levels:
    critical:
      - "配置文件不存在"
      - "无法加载配置"
      - "关键配置缺失"
    warning:
      - "配置更新延迟"
      - "配置格式警告"
      - "质量评分偏低"
    info:
      - "建议优化配置"
      - "性能提醒"

# 组件配置处理器设置
component_handlers:
  database:
    config_patterns:
      - "database.*"
      - "mysql.*"
      - "clickhouse.*"
    validation_rules:
      - name: "connection_check"
        enabled: true
      - name: "credential_check"
        enabled: true
        
  storage:
    config_patterns:
      - "storage.*"
      - "storage_layers.*"
    validation_rules:
      - name: "layer_connectivity"
        enabled: true
      - name: "capacity_check"
        enabled: true
        
  monitoring:
    config_patterns:
      - "monitoring.*"
      - "alerts.*"
    validation_rules:
      - name: "endpoint_check"
        enabled: true
      - name: "threshold_validation"
        enabled: true

# 故障恢复配置
fault_tolerance:
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 60
    expected_exception: "Exception"
  retry_policy:
    max_attempts: 3
    backoff_factor: 2
    initial_delay: 1
  fallback_strategy:
    config_file_fallback: true
    default_config_fallback: true
    emergency_config_path: "./config/emergency"

# 版本管理配置
version_management:
  enabled: true
  version_format: "v{major}.{minor}.{patch}"
  auto_increment: true
  backup_on_change: true
  max_versions: 50
  
# 环境特定配置
environments:
  development:
    change_detection_interval: 0.5
    validation_timeout: 15.0
    backup_count: 5
    auto_reload: true
    
  testing:
    change_detection_interval: 1.0
    validation_timeout: 20.0
    backup_count: 3
    auto_reload: false
    
  production:
    change_detection_interval: 5.0
    validation_timeout: 60.0
    backup_count: 20
    auto_reload: true
    alerting:
      enabled: true
      levels:
        critical:
          action: "immediate_alert"
        warning:
          action: "delayed_alert"

# 安全配置
security:
  file_permissions:
    config_files: "640"
    backup_files: "600"
    log_files: "644"
  encryption:
    enabled: false
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
  access_control:
    enabled: true
    allowed_users: []
    allowed_groups: ["admin", "config_managers"]

# 集成配置
integrations:
  # 与现有配置系统集成
  config_manager:
    enabled: true
    integration_mode: "embedded"
    sync_interval: 30
    
  # 与监控系统集成
  monitoring_system:
    enabled: true
    metrics_endpoint: "/metrics/config"
    health_endpoint: "/health/config"
    
  # 与告警系统集成
  alerting_system:
    enabled: true
    webhook_urls: []
    notification_channels: ["email", "slack"]